language: objective-c
osx_image: xcode8.1
xcode_project: openxc-ios-framework.xcodeproj
xcode_scheme: openxc-ios-framework
xcode_sdk: iphonesimulator10.1

branches:
- master

script:
- xcodebuild clean build test -project openxc-ios-framework.xcodeproj -scheme openxc-ios-framework -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1'  ONLY_ACTIVE_ARCH=NO


